# (OpenCV - Chap5) 10월 13일(2)
> 사칙연산, 지수, 로그, 제곱근 함수

- toc: true
- branch: master
- badges: false
- comments: true
- author: pinkocto
- categories: [python]

### 5.3.1 사칙 연산 (행렬 산술 연산)

사칙연산을 위한 OpenCV함수에 대해 알아보자.

- **`cv2.add(src1, src2[, mask[, dtype]]]) -> dst`**
    - 두 개의 배열 혹은 배열과 스칼라의 각 원소 간 합을 계산한다. 입력인수 src1, src2 중 하나는 스칼라값일 수 있다.
    
        - $dst(i) = saturate(src1(i) + src2(i)) \quad \text{if } mask(i) \neq 0$
        - $dst(i) = saturate(src1 + src2(i)) \quad \text{if } mask(i) \neq 0$
        - $dst(i) = saturate(src1(i) + src2) \quad \text{if } mask(i) \neq 0$
        
        
- **`cv2.addWeighted(src1, alpha1, src2, beta, gamma[,[dst[,dtype]]) -> dst`**
    - 두 배열의 각 원소에 가중치를 곱한 후에 각 원소 간 합 즉, 가중된(weighted) 합을 계산한다.
    - 수식: $dst(i) = saturate(src1(i)\cdot\alpha + src2(i)\cdot \beta + \gamma)$

<div class="alert-success">
[ 참고 ]

OpenCV에서 **saturate()** 는 0이하는 0으로, 255이상은 255로 범위를 한정시키는 연산이다.
</div>

In [1]:
#collapse-hide
import numpy as np, cv2

m1 = np.full((3,6), 10, np.uint8)           # 단일채널 생성 및 초기화
m2 = np.full((3,6), 50, np.uint8)          
m_mask = np.zeros(m1.shape, np.uint8)       # 마스크 생성
m_mask[:,3:] = 1                            # 관심 영역(모든행, 3열부터)을 지정한 후, 1을 할당

In [2]:
m1

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]], dtype=uint8)

In [3]:
m2

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]], dtype=uint8)

In [4]:
m_mask

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]], dtype=uint8)

`-` 행렬 덧셈

In [5]:
m_add1 = cv2.add(m1, m2)
m_add1

array([[60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60]], dtype=uint8)

In [7]:
m_add2 = cv2.add(m1, m2, mask=m_mask)
m_add2

array([[ 0,  0,  0, 60, 60, 60],
       [ 0,  0,  0, 60, 60, 60],
       [ 0,  0,  0, 60, 60, 60]], dtype=uint8)

- 마스크 영역 (관심영역)만 덧셈 연산이 된 것을 확인!

`-` 행렬 나눗셈

In [8]:
m_div1 = cv2.divide(m1, m2)
m_div1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=uint8)

- 전부 0으로 나온다? 0.2가 나와야 하는데?? (소수 부분이 상실되었다.)

`-` 소수부분 소실 방지

행렬 원소 자료형을 32비트 실수형(np.float32)로 변환

In [9]:
m1 = m1.astype(np.float32)           # 소수부분 보존위해 행변환
m2 = np.float32(m2)                  # 형 변환 방법2
m_div2 = cv2.divide(m1, m2)
m_div2

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]], dtype=float32)

- 소수부분 소실 문제가 잘 해결되었다.

### 5.3.2 지수, 로그, 제곱근 관련 함수

In [10]:
#collapse-hide
import numpy as np, cv2

## ndarray 생성
v1 = np.array([1,2,3], np.float32)          # 1차원 리스트로 행렬 생성
v2 = np.array([[1],[2],[3]], np.float32)    # 2차원 리스트 (3행, 1열) - 열벡터
v3 = np.array([[1,2,3]],np.float32)         # 2차원 리스트 (1행, 3열) - 행벡터

In [11]:
v1        # 1차원 리스트로 행렬 생성

array([1., 2., 3.], dtype=float32)

In [12]:
v2        # 2차원 리스트 (3행, 1열) - 열벡터

array([[1.],
       [2.],
       [3.]], dtype=float32)

In [13]:
v3       # 2차원 리스트 (1행, 3열) - 행벡터

array([[1., 2., 3.]], dtype=float32)

In [16]:
#collapse-hide
v_exp = cv2.exp(v1)        # 1차원 행렬에 대한 지수
m_exp = cv2.exp(v2)        # 행벡터 (1*3)에 대한 지수계산
m_exp = cv2.exp(v3)        # 열벡터 (3*1)에 대한 지수 계산
v_log = cv2.log(v1)        # 로그 계산
m_sqrt = cv2.sqrt(v2)      # 제곱근 계산
m_pow = cv2.pow(v3, 3)     # 3의 거듭제곱 계산

In [17]:
# cv2.exp
v_exp

array([[ 2.718282 ],
       [ 7.3890557],
       [20.085539 ]], dtype=float32)

In [27]:
# np.exp
np.array([[np.exp(1)], [np.exp(2)],[np.exp(3)]])

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

- 잘 계산되는구만!

In [18]:
m_exp

array([[ 2.718282 ,  7.3890557, 20.085539 ]], dtype=float32)

In [19]:
v_log

array([[0.       ],
       [0.6931472],
       [1.0986123]], dtype=float32)

In [20]:
m_sqrt

array([[1.       ],
       [1.4142135],
       [1.7320508]], dtype=float32)

In [21]:
m_pow

array([[ 1.,  8., 27.]], dtype=float32)