# (OpenCV - Chap5) 10월 13일(2)
> 사칙연산, 지수, 로그, 제곱근 함수

- toc: true
- branch: master
- badges: false
- comments: true
- author: pinkocto
- categories: [python]

### 5.3.1 사칙 연산 (행렬 산술 연산)

In [1]:
#collapse-hide
import numpy as np, cv2

m1 = np.full((3,6), 10, np.uint8)           # 단일채널 생성 및 초기화
m2 = np.full((3,6), 50, np.uint8)          
m_mask = np.zeros(m1.shape, np.uint8)       # 마스크 생성
m_mask[:,3:] = 1                            # 관심 영역(모든행, 3열부터)을 지정한 후, 1을 할당

In [2]:
m1

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]], dtype=uint8)

In [3]:
m2

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]], dtype=uint8)

In [4]:
m_mask

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]], dtype=uint8)

`-` 행렬 덧셈

In [5]:
#collapse-hide
m_add1 = cv2.add(m1, m2)
m_add1

array([[60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60]], dtype=uint8)

In [7]:
#collapse-hide
m_add2 = cv2.add(m1, m2, mask=m_mask)
m_add2

array([[ 0,  0,  0, 60, 60, 60],
       [ 0,  0,  0, 60, 60, 60],
       [ 0,  0,  0, 60, 60, 60]], dtype=uint8)

- 마스크 영역 (관심영역)만 덧셈 연산이 된 것을 확인!

`-` 행렬 나눗셈

In [8]:
#collapse-hide
m_div1 = cv2.divide(m1, m2)
m_div1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=uint8)

- 전부 0으로 나온다? 0.2가 나와야 하는데?? (소수 부분이 상실되었다.)

`-` 소수부분 소실 방지

행렬 원소 자료형을 32비트 실수형(np.float32)로 변환

In [9]:
#collapse-hide
m1 = m1.astype(np.float32)           # 소수부분 보존위해 행변환
m2 = np.float32(m2)                  # 형 변환 방법2
m_div2 = cv2.divide(m1, m2)
m_div2

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]], dtype=float32)

- 소수부분 소실 문제가 잘 해결되었다.

### 5.3.2 지수, 로그, 제곱근 관련 함수

In [ ]:
#collapse-hide
import numpy as np, cv2

## ndarray 생성
v1 = np.array([1,2,3], np.float32)          # 1차원 리스트로 행렬 생성
v2 = np.array([[1],[2],[3]], np.float32)    # 2차원 리스트 (3행, 1열) - 열벡터
v3 = np.array([[1,2,3]])